locallibrary/catalog/urls.py
from django.urls import path
from catalog import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    # path(r'^book.*\?from=\d{4}.\d{2}.\d{2}.*&to=\d{4}.\d{2}.\d{2}', views.BookDateRangeView.as_view(), name='book_dates')
]

locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
# from catalog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

locallibrary/catalog/models.py
from django.db import models
from django.urls import reverse #Used to generate urls by reversing the URL patterns
import uuid # Required for unique book instances
from datetime import date
from django.contrib.auth.models import User #Required to assign User as a borrower


class Genre(models.Model):
    """
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """
    name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)")

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name


class Language(models.Model):
    """
    Model representing a Language (e.g. English, French, Japanese, etc.)
    """
    name = models.CharField(max_length=200, help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name


class Book(models.Model):
    """
    Model representing a book (but not a specific copy of a book).
    """
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
      # Foreign Key used because book can only have one author, but authors can have multiple books
      # Author as a string rather than object because it hasn't been declared yet in file.
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN',max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
      # ManyToManyField used because a genre can contain many books and a Book can cover many genres.
      # Genre class has already been defined so we can specify the object above.
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    def display_genre(self):
        """
        Creates a string for the Genre. This is required to display genre in Admin.
        """
        return ', '.join([ genre.name for genre in self.genre.all()[:3] ])
        display_genre.short_description = 'Genre'


    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('book-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title


class BookInstance(models.Model):
    """
    Model representing a specific copy of a book (i.e. that can be borrowed from the library).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False


    LOAN_STATUS = (
        ('d', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status= models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='d', help_text='Book availability')

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        """
        String for representing the Model object.
        """
        #return '%s (%s)' % (self.id,self.book.title)
        return '{0} ({1})'.format(self.id,self.book.title)


class Author(models.Model):
    """
    Model representing an author.
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    class Meta:
        ordering = ["last_name","first_name"]

    def get_absolute_url(self):
        """
        Returns the url to access a particular author instance.
        """
        return reverse('author-detail', args=[str(self.id)])


    def __str__(self):
        """
        String for representing the Model object.
        """
        return '{0}, {1}'.format(self.last_name,self.first_name)

locallibrary/catalog/views.py
from django.shortcuts import render
from catalog.models import Book, Author, BookInstance, Genre
from django.views import generic

def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()
    num_genres = Genre.objects.count()
    num_books_containing_analysis = Book.objects.filter(title__icontains='analysis').count()

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_genres': num_genres,
        'num_books_containing_analysis': num_books_containing_analysis,
    }

    return render(request, 'index.html', context=context)

class BookListView(generic.ListView):
    model = Book
    paginate_by = 3  # to access page 2 you would use the URL: /catalog/books/?page=2.

class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author
    # paginate_by = 3  # to access page 2 you would use the URL: /catalog/books/?page=2.

class AuthorDetailView(generic.DetailView):
    model = Author

locallibrary/catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <!-- Add additional CSS in static file -->
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        <div class="container-fluid">
            <div class="row bg-dark">
                <div class="col">
                </div>

                <div class="col-6">
                    <nav class="navbar navbar-expand-lg navbar-dark">
                        <a class="navbar-brand" href="#">My book reviews</a>
                        <div class="navbar">
                            {% block sidebar %}
                                <ul class="navbar-nav mr-auto">
                                    <li class="nav-item"><a class="nav-link" href="{% url 'index' %}">Home</a></li>
                                    <li class="nav-item"><a class="nav-link" href="{% url 'books' %}">All books</a></li>
                                    <li class="nav-item"><a class="nav-link" href="{% url 'authors' %}">All authors</a></li>
                                </ul>
                            {% endblock %}
                        </div>
                    </nav>
                </div>

                <div class="col">
                </div>

            </div>

            <div class="row  pt-5">
                <div class="col">
                </div>



                <div class="col-6">
                    {% block title %}{% endblock title%}
                    {% block content %}{% endblock content %}
                    {% block pagination %}
                    {% if is_paginated %}
                    <div class="pagination">
                        <span class="page-links">
                            {% if page_obj.has_previous %}
                                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous - </a>
                            {% endif %}
                        <span class="page-current">
                            {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
                        </span>
                            {% if page_obj.has_next %}
                                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}"> - next</a>
                            {% endif %}
                        </span>
                    </div><
                    {% endif %}
                    {% endblock pagination %}
                </div>

                <div class="col">
                </div>

            </div>
        </div>
    </body>
</html>

locallibrary/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1 class="row">Author details</h1>

        <table class="py-3">
            <tr>
                <td><strong>First name:</strong></td>
                <td>{{ author.first_name }}</td>
            </tr>
            <tr>
                <td><strong>Last name:</strong></td>
                <td>{{ author.last_name }}</td>
            </tr>
            <tr>
                <td><strong>Date of birth:</strong></td>
                <td>{{ author.date_of_birth }}</td>
            </tr>
            <tr>
                <td><strong>Date of death:</strong></td>
                <td>{{ author.date_of_death }}</td>
            </tr>
        </table>

    <h3 class="row py-3">Books by the author</h3>
    {% for book in author.book_set.all %}
        <div class="row">
            <a href="{{book.get_absolute_url}}">{{book.title}}</a></br>
            {{book.summary}}
        </div>
    {% endfor %}

{% endblock %}

locallibrary/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Author List</h1>
    {% if author_list %}
        <ul>
            {% for author in author_list %}
                <li>
                    <a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{ author.last_name }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no authors in the library.</p>
    {% endif %}
{% endblock content %}

locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Title: {{ book.title }}</h1>

    <p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
    <p><strong>Summary:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Language:</strong> {{ book.language }}</p>
    <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

    <div style="margin-left:20px;margin-top:20px">

        <h4>Copies</h4>

        {% for copy in book.bookinstance_set.all %}

            <hr>
            <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
            {% if copy.status != 'a' %}
                <p><strong>Due to be returned:</strong> {{copy.due_back}}</p>
            {% endif %}
            <p><strong>Imprint:</strong> {{copy.imprint}}</p>
            <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>

        {% endfor %}

    </div>

{% endblock %}

locallibrary/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Book List</h1>
    {% if book_list %}
        <ul>
            {% for book in book_list %}
                <li>
                    <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>({{ book.author }})
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no books in the library.</p>
    {% endif %}
{% endblock content %}

locallibrary/catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
  <p>Welcome to my book collection</p>
  <h2>Overview</h2>
  <p>Here are some stats:</p>
  <table>
    <tr>
        <td class="p-1"><strong>Books:</strong></td>
        <td class="p-1">{{ num_books }}</td>
    </tr>
    <tr>
        <td class="p-1"><strong>Copies:</strong></td>
        <td class="p-1">{{ num_instances }}</td>
    </tr>
    <tr>
        <td class="p-1"><strong>Copies available:</strong></td>
        <td class="p-1">{{ num_instances_available }}</td>
    </tr>
    <tr>
        <td class="p-1"><strong>Authors:</strong></td>
        <td class="p-1">{{ num_authors }}</td>
    </tr>
    <tr>
        <td class="p-1"><strong>Genres:</strong></td>
        <td class="p-1">{{ num_genres }}</td>
    </tr>
    <tr>
        <td class="p-1"><strong>Books with the word 'Analysis' :</strong></td>
        <td class="p-1">{{ num_books_containing_analysis }}</td>
    </tr>
  </table>
{% endblock %}